### ISSUE TITLE
Incorrect comment in webserver.ino header

### ISSUE THREAD

**Issue by darrenklein** [PacktPublishing/Creative-DIY-Microcontroller-Projects#1]
Hello - I was just glancing through some of the code, and I noticed that the comment in the file `Chapter10/webserver/webserver.ino` appears to be incorrect - it reads

```
/**
  Creative DIY Microcontroller Projects with C, published by Packt
  Chapter 10: IoT plant pot moisture sensor.
  Read sensor values from the SMT32 Blue Pill 
  and creates on the NodeMCU a web server to display the data.
  By Pedro Santana
  Ver. 1
  April, 2021
*/
```

but the code in that file (as indicated by the file name) is for a web server - but one of the other directories in Chapter 10 is for a moisture sensor...

**Comment by pecesama** [comment]
Dear @darrenklein, thank you for your comment. The comments look correct to me. This sketch read a value coming from the STM32 by pin 4 on the NodeMCU and then show that data on the web page hosted into the webserver embedded on this sketch. The value comes from a Blue Pill connected to a moisture sensor that reads it and sends it to the NodeMCU (moisture sketch). Please, tell me if I am missing something.

**Comment by darrenklein** [comment]
My apologies, I must've misunderstood. Thanks very much for looking into this and getting back to me.

**Comment by pecesama** [comment]
Thanks to you for getting in touch with us. I hope our book can be useful.
